[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino  

; --- 核心硬件配置 (N16R8: 16MB Flash + 8MB PSRAM) ---
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi ; Octal SPI 模式，支持 8MB PSRAM
board_build.partitions = partitions_16MB.csv ; 自定义 16MB 分区表

; --- 编译选项 ---
build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; 通过 USB 直接调试

